device: 'cuda'
model_save_path: 'model/save.pt'
bin_model_save_path: 'model/save.bin'
#CONFIGURE DATASET PATH SPECIFIC TO YOUR SETUP:
copy_data_to_mem: no
only_quiet: yes
nnue_bin_data_path: /home/connor/nnue_data/bin/100md12train.bin
num_workers: 1
batch_size: 64
lambda_: 0.75

visual_directory: 'visual'

epochs: 10000000
save_rate: 10000
report_rate: 4
test_rate: 8
max_queue_size: 128


learning_rate: 1.00
