device: 'cuda'
model_save_path: 'model/save.pt'
bin_model_save_path: 'model/save.bin'
#CONFIGURE DATASET PATH SPECIFIC TO YOUR SETUP:
only_quiet: yes
nnue_bin_data_path: /home/connor/nnue_data/bin/100md12train.bin
#nnue_bin_data_path: /media/connor/7F35A067038168A9/1bil-d8.bin
shuffle_buffer_size: 100000
enable_mirroring: yes
num_workers: 2
batch_size: 128
lambda_: 0.75

visual_directory: 'visual'

epochs: 10000000
save_rate: 10000
report_rate: 10
test_rate: 10
max_queue_size: 128


learning_rate: 1.00
