device: 'cuda'
model_save_path: 'model/save.pt'
bin_model_save_path: 'model/save.bin'
#CONFIGURE DATASET PATH SPECIFIC TO YOUR SETUP:
dataset_path: '/home/connor/nnue_data'
visual_directory: 'visual'

epochs: 100000
epoch_length: 210000
report_rate: 4
test_rate: 8
max_queue_size: 128
batch_size: 56

learning_rate: 1.0

max_fullmoves: 256
uci_engine_path: '/usr/games/stockfish'
uci_engine_time: 0.01
interpolation_factor: 0.3
num_positions: 10000000



