device: 'cuda'
model_save_path: 'model/save.pt'
bin_model_save_path: 'model/save.bin'
only_quiet: yes
train_bin_data_path: /home/connor/nnue_data/bin/100millionDepth12.bin
#train_bin_data_path: /media/connor/7F35A067038168A9/1bil-d8.bin

validation_bin_data_path: /home/connor/nnue_data/bin/1_million_depth_21.bin

shuffle_buffer_size: 100000
enable_mirroring: yes
num_workers: 4
batch_size: 512
lambda_: 0.8

visual_directory: 'visual'

epochs: 10000000
save_rate: 10000
report_rate: 50
test_rate: 50
max_queue_size: 128


learning_rate: 0.5
