device: 'cuda'
model_save_path: 'model/save.pt'
bin_model_save_path: 'model/save.bin'
only_quiet: no
train_bin_data_path: /media/connor/7F35A067038168A9/resolved/train.bin
#train_bin_data_path: /media/connor/7F35A067038168A9/1bil-d8.bin

validation_bin_data_path: /media/connor/7F35A067038168A9/resolved/val.bin

shuffle_buffer_size: 100000
enable_mirroring: yes
num_workers: 6
batch_size: 384
lambda_: 1.0

visual_directory: 'visual'

epochs: 10000000
save_rate: 10000
report_rate: 50
test_rate: 50
max_queue_size: 128


learning_rate: 1.5
